### PR TITLE
Update v4

### PR DESCRIPTION
**Pull request by mmarkelov**
Replace instanceRef with applyRef

### CODE REVIEW

**Comment by mmarkelov** [comment]
Can't implement documentation for GeoObject, cauze it throw **TypeError: GeoObject is not a constructor** - don't understand what is wrong (

**Comment by gribnoysup** [comment]
I'll merge what is in this branch already, I have a bunch of stuff done in my local branch already and I'm worried that we are doing the same thing :D

**Comment by mmarkelov** [comment]
@gribnoysup sorry, I should tell you about this :(

**Comment by gribnoysup** [comment]
No worries, man, all good! Thanks for helping out with this stuff 😁

**Pull request merged**
