### PR TITLE
Added flexible wrapper

### PR DESCRIPTION
**Pull request by Nimmimarco**

### CODE REVIEW

**Comment by gribnoysup** [comment]
Hi @Nimmimarco, thank you for your pull request. 

1) Please, describe the issue you are trying to solve with this
2) Compiled source shouldn't be included in this repo

**Comment by Nimmimarco** [comment]
Hi @gribnoysup, thank for nice rep.
I trying to set width and height to 100%.
Example:
```javascript
<YMaps>
  <Map width={'100%'} height={'100%'} state={{...mapState, center: focusedPoint, zoom }}>
    ...
  </Map>
</YMaps>

**Comment by gribnoysup** [comment]
@Nimmimarco okay, now I understand the problem, but the solution you provided could introduce bugs in some cases, because height in percents is calculated from the width of the element. I made some tests and it seems that render method of map could be changed to this:

```jsx
return this.context.ymaps &&
      <div style={{ width, height }} ref={this.getMapNode}>
        {this.children}
      </div>;
```

I think this will allow you to do what you want. Could you try this solution and see if it resolves your problem? If it is I'll accept this solution as your PR if you want :)

**Comment by Nimmimarco** [comment]
@gribnoysup yeap, thank, this solution also work for me. i just thought the second div is necessary for something.

**Comment by gribnoysup** [comment]
@Nimmimarco When I was doing this, I was sure for some reason that yandex maps api replaces content of dom node on map render. This is not true apparently :smile: Thank you for your contribution!

**Pull request merged**
